
services:
  nest-app:
    build:
      context: .
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=1228
      - DB_NAME=ecommerceDB
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    networks:
      - app-network

  postgres_db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1228
      POSTGRES_DB: ecommerceDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
